using Content.Client.UserInterface.Controls;
using Content.Shared.Vanilla.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Vanilla.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ParaxitExtractorMenu : FancyWindow
{
    public event Action? OnServerButtonPressed;
    public event Action? OnExtractButtonPressed;

    public ParaxitExtractorMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        ExtractButton.OnPressed += _ => OnExtractButtonPressed?.Invoke();
    }

    public void Update(ParaxitExtractorBoundUserInterfaceState state)
    {
        ExtractButton.Disabled = !state.CanExtract;
        TotalLabel.Text = Loc.GetString("paraxit-extractor-total-label", ("amount", state.ServerAdvancedPoints));
        CostLabel.Text = Loc.GetString("paraxit-extractor-ui-cost-label", ("amount", state.PointCost));
    }
}